#!/usr/bin/env python3
"""
Build the men's / unisex price-per-pure-gold-oz leaderboard.

Source of truth is data/rings.json, which scripts/build_rings.py compiles from
data/evidence/*.json. Nothing here is hand-entered: every value is derived from a
row that already carries a first-party source_url.

Outputs:
  docs/MENS_LEADERBOARD.md
  docs/data/mens_price_per_oz_leaderboard.json
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
THRESHOLD = 6000.0  # user-directed threshold 2026-08-28 (session 9): "lower prices than Price / Gold Oz $6000 /oz Mens" (supersedes session-7's $5,500)

# Spot quotes read on 2026-08-28 (session 7; see docs/REVIEW_2026-08-28.md section 1):
#   cnbc.com/select    $4,598.89 (9:00 a.m. ET 2026-08-28)
#   usatoday.com       $4,522.93 (12:05 p.m. ET 2026-08-28)
# The premium column uses their midpoint, stated explicitly so it is auditable.
SPOT_LOW = 4522.93
SPOT_HIGH = 4598.89
SPOT = round((SPOT_LOW + SPOT_HIGH) / 2, 2)  # 4560.91

MEN_RE = re.compile(r"\b(men|mens|men's|gents|gentleman|gentlemen's|unisex|male)\b", re.I)
WOMEN_RE = re.compile(r"\bwomen'?s?\b", re.I)


def is_mens(row):
    """A row counts as men's/unisex if its name or note says so, and it is not
    a women-only listing that merely contains the substring 'men'."""
    blob = f"{row.get('ring') or ''} || {row.get('note') or ''}"
    if not MEN_RE.search(blob):
        return False
    if WOMEN_RE.search(blob) and not MEN_RE.search(row.get("ring") or "", re.I):
        return False
    return True


def signed_pct(value):
    """Render a percentage with a real sign, e.g. -18% / +34%. (A naive
    '+{:.0f}%' produces the malformed '+-18%' for negative values.)"""
    return f"{value:+.0f}%"


def main():
    src = os.path.join(ROOT, "data", "rings.json")
    rows = json.load(open(src))

    cand = sorted(
        (r for r in rows if r.get("price_per_gold_oz") and is_mens(r)),
        key=lambda r: r["price_per_gold_oz"],
    )

    payload = {
        "generated_from": "data/rings.json (compiled from data/evidence/*.json; no hand-entered values)",
        "regenerate_with": "python3 scripts/build_mens_leaderboard.py",
        "threshold_usd_per_pure_gold_oz": THRESHOLD,
        "spot_usd_per_oz_used_for_premium": SPOT,
        "spot_basis": f"midpoint of ${SPOT_LOW} (usatoday.com 12:05 ET) and ${SPOT_HIGH} (cnbc.com/select 9:00 ET), 2026-08-28",
        "men_filter": (
            r"regex \b(men|mens|men's|gents|gentleman|unisex|male)\b applied to ring name + note; "
            "women-only rows excluded"
        ),
        "total_rows_in_dataset": len(rows),
        "rows_with_price_per_gold_oz": sum(1 for r in rows if r.get("price_per_gold_oz")),
        "mens_rows_with_price_per_gold_oz": len(cand),
        "mens_rows_below_threshold": sum(1 for r in cand if r["price_per_gold_oz"] < THRESHOLD),
        "rows": [
            {
                "rank": i,
                "id": r["id"],
                "ring": r["ring"],
                "seller": r["seller"],
                "karat": r["karat"],
                "weight_g": r.get("weight_g"),
                "price_usd": r.get("price_usd"),
                "price_per_gold_oz": r["price_per_gold_oz"],
                "below_threshold": r["price_per_gold_oz"] < THRESHOLD,
                "premium_over_melt_pct": round((r["price_per_gold_oz"] / SPOT - 1) * 100, 1),
                "source_url": r["source_url"],
                "verified_on": r.get("verified_on"),
            }
            for i, r in enumerate(cand, 1)
        ],
    }

    n = len(cand)
    below = payload["mens_rows_below_threshold"]
    L = []
    L.append("# Men's / Unisex Rings Ranked by Price per Pure Gold Troy Ounce\n")
    L.append(
        "_Generated by `scripts/build_mens_leaderboard.py` from `data/rings.json`, which is compiled from "
        "`data/evidence/*.json`. Every number below traces to an evidence file with an official source link — "
        "none is hand-entered._\n"
    )
    L.append(
        f"**Threshold:** ${THRESHOLD:,.2f} / pure gold troy oz  ·  **Spot used for the premium column:** "
        f"${SPOT:,.2f}/oz (midpoint of ${SPOT_LOW:,.2f} USA Today 12:05 ET – ${SPOT_HIGH:,.2f} CNBC 9:00 ET, 2026-08-28)\n"
    )
    L.append(
        f"**Population:** {len(rows)} rows in the directory · {payload['rows_with_price_per_gold_oz']} have a "
        f"computable price/oz · **{n} are men's/unisex** · **{below} are below the threshold.**\n"
    )
    L.append(
        f"> ⚠️ **This is the complete list, not a top-N cut.** The dataset contains only {n} men's/unisex rows "
        "with a published weight *and* a published price, so a 50-row men's list cannot be produced from "
        f"verified data. Rows 1–{below} clear the threshold; the rest do not.\n"
    )
    L.append(
        "| # | Price / gold oz | vs melt | Seller | Ring | Karat | Weight | Price | Verified | Official source |"
    )
    L.append("|---|---|---|---|---|---|---|---|---|---|")
    for r in payload["rows"]:
        flag = "✅" if r["below_threshold"] else "❌"
        prem = signed_pct((r["price_per_gold_oz"] / SPOT - 1) * 100)
        L.append(
            f"| {r['rank']} | {flag} **${r['price_per_gold_oz']:,.2f}** | {prem} | {r['seller']} | "
            f"{r['ring'][:60]} | {r['karat']} | {r['weight_g']} g | ${r['price_usd']:,.2f} | "
            f"{r['verified_on']} | [link]({r['source_url']}) |"
        )
    L.append("")
    L.append("### Reading this table\n")
    from collections import Counter
    passing = [r for r in payload["rows"] if r["below_threshold"]]
    per_seller = Counter(r["seller"] for r in passing)
    L.append(
        f"- **Rows 1–{below}** clear the current threshold of **${THRESHOLD:,.0f}/pure-gold-oz** (user-directed "
        f"2026-08-28; = melt +{(THRESHOLD / SPOT - 1) * 100:.0f}% at the spot basis above). Composition: "
        + ", ".join(f"**{n}× {seller}**" for seller, n in per_seller.most_common())
        + ". The Midwest rows are closeout 14K men's mountings **9–18% below melt** (setting-only, not normal "
        "retail). The 2026-08-28 rows are the 1/4 oz .9999 Nebü bullion-ring family (+8% to +21% over melt), each "
        "with price and weight read live on official pages; SD Bullion's pair is **out of stock**, and JM Bullion's "
        "price is the ACH/Check tier (their card tier $1,395.99 = $5,589.80/oz would FAIL) — both stated in the "
        "evidence notes."
    )
    L.append(
        f"- **Rows {below + 1}+** fail the threshold: Provident Metals' 10.5 g 24K men's curved ring (cheapest "
        "verified 24K men's ring, +36%), Costco (per-size weights published, but prices do not render in a plain "
        "fetch — see docs/REVIEW_2026-08-28.md §6.1), and Ritani 14K/18K men's bands at +89% to +244% over melt. "
        "They stay listed to show the true shape of the market."
    )
    L.append(
        f"- The `vs melt` column is why a 50-entry target is unreachable: only {n} men's/unisex rows in the 479-row "
        "directory publish BOTH a price and a gram weight, and every channel family measured across seven review "
        "sessions (≈50 channels) sits at melt +16% or higher except US closeout mountings and the 1/4 oz "
        "bullion-ring family. Full channel-by-channel links and math: `docs/REVIEW_2026-08-28.md`."
    )

    md_path = os.path.join(ROOT, "docs", "MENS_LEADERBOARD.md")
    json_path = os.path.join(ROOT, "docs", "data", "mens_price_per_oz_leaderboard.json")
    os.makedirs(os.path.dirname(json_path), exist_ok=True)
    open(md_path, "w").write("\n".join(L) + "\n")
    json.dump(payload, open(json_path, "w"), indent=1)

    print(f"wrote {md_path}")
    print(f"wrote {json_path}")
    print(
        f"  {n} men's/unisex rows with price/oz | {below} below ${THRESHOLD:,.0f} | "
        f"{payload['rows_with_price_per_gold_oz']} of {len(rows)} rows have price/oz"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
