#!/usr/bin/env python3
"""
Build the men's / unisex price-per-pure-gold-oz leaderboard.

Source of truth is data/rings.json, which scripts/build_rings.py compiles from
data/evidence/*.json. Nothing here is hand-entered: every value is derived from a
row that already carries a first-party source_url.

Outputs:
  docs/MENS_LEADERBOARD.md
  docs/data/mens_price_per_oz_leaderboard.json
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
THRESHOLD = 4861.0

# Spot quotes read on 2026-08-27 (see docs/REVIEW_2026-08-27.md section 1):
#   cnbc.com/select    $4,584.96
#   usagold.com        $4,648.90
# The premium column uses their midpoint, stated explicitly so it is auditable.
SPOT_LOW = 4584.96
SPOT_HIGH = 4648.90
SPOT = round((SPOT_LOW + SPOT_HIGH) / 2, 2)  # 4616.93

MEN_RE = re.compile(r"\b(men|mens|men's|gents|gentleman|gentlemen's|unisex|male)\b", re.I)
WOMEN_RE = re.compile(r"\bwomen'?s?\b", re.I)


def is_mens(row):
    """A row counts as men's/unisex if its name or note says so, and it is not
    a women-only listing that merely contains the substring 'men'."""
    blob = f"{row.get('ring') or ''} || {row.get('note') or ''}"
    if not MEN_RE.search(blob):
        return False
    if WOMEN_RE.search(blob) and not MEN_RE.search(row.get("ring") or "", re.I):
        return False
    return True


def signed_pct(value):
    """Render a percentage with a real sign, e.g. -18% / +34%. (A naive
    '+{:.0f}%' produces the malformed '+-18%' for negative values.)"""
    return f"{value:+.0f}%"


def main():
    src = os.path.join(ROOT, "data", "rings.json")
    rows = json.load(open(src))

    cand = sorted(
        (r for r in rows if r.get("price_per_gold_oz") and is_mens(r)),
        key=lambda r: r["price_per_gold_oz"],
    )

    payload = {
        "generated_from": "data/rings.json (compiled from data/evidence/*.json; no hand-entered values)",
        "regenerate_with": "python3 scripts/build_mens_leaderboard.py",
        "threshold_usd_per_pure_gold_oz": THRESHOLD,
        "spot_usd_per_oz_used_for_premium": SPOT,
        "spot_basis": f"midpoint of ${SPOT_LOW} (cnbc.com/select) and ${SPOT_HIGH} (usagold.com), 2026-08-27",
        "men_filter": (
            r"regex \b(men|mens|men's|gents|gentleman|unisex|male)\b applied to ring name + note; "
            "women-only rows excluded"
        ),
        "total_rows_in_dataset": len(rows),
        "rows_with_price_per_gold_oz": sum(1 for r in rows if r.get("price_per_gold_oz")),
        "mens_rows_with_price_per_gold_oz": len(cand),
        "mens_rows_below_threshold": sum(1 for r in cand if r["price_per_gold_oz"] < THRESHOLD),
        "rows": [
            {
                "rank": i,
                "id": r["id"],
                "ring": r["ring"],
                "seller": r["seller"],
                "karat": r["karat"],
                "weight_g": r.get("weight_g"),
                "price_usd": r.get("price_usd"),
                "price_per_gold_oz": r["price_per_gold_oz"],
                "below_threshold": r["price_per_gold_oz"] < THRESHOLD,
                "premium_over_melt_pct": round((r["price_per_gold_oz"] / SPOT - 1) * 100, 1),
                "source_url": r["source_url"],
                "verified_on": r.get("verified_on"),
            }
            for i, r in enumerate(cand, 1)
        ],
    }

    n = len(cand)
    below = payload["mens_rows_below_threshold"]
    L = []
    L.append("# Men's / Unisex Rings Ranked by Price per Pure Gold Troy Ounce\n")
    L.append(
        "_Generated by `scripts/build_mens_leaderboard.py` from `data/rings.json`, which is compiled from "
        "`data/evidence/*.json`. Every number below traces to an evidence file with an official source link — "
        "none is hand-entered._\n"
    )
    L.append(
        f"**Threshold:** ${THRESHOLD:,.2f} / pure gold troy oz  ·  **Spot used for the premium column:** "
        f"${SPOT:,.2f}/oz (midpoint of ${SPOT_LOW:,.2f} CNBC – ${SPOT_HIGH:,.2f} USAGOLD, 2026-08-27)\n"
    )
    L.append(
        f"**Population:** {len(rows)} rows in the directory · {payload['rows_with_price_per_gold_oz']} have a "
        f"computable price/oz · **{n} are men's/unisex** · **{below} are below the threshold.**\n"
    )
    L.append(
        f"> ⚠️ **This is the complete list, not a top-N cut.** The dataset contains only {n} men's/unisex rows "
        "with a published weight *and* a published price, so a 50-row men's list cannot be produced from "
        f"verified data. Rows 1–{below} clear the threshold; the rest do not.\n"
    )
    L.append(
        "| # | Price / gold oz | vs melt | Seller | Ring | Karat | Weight | Price | Verified | Official source |"
    )
    L.append("|---|---|---|---|---|---|---|---|---|---|")
    for r in payload["rows"]:
        flag = "✅" if r["below_threshold"] else "❌"
        prem = signed_pct((r["price_per_gold_oz"] / SPOT - 1) * 100)
        L.append(
            f"| {r['rank']} | {flag} **${r['price_per_gold_oz']:,.2f}** | {prem} | {r['seller']} | "
            f"{r['ring'][:60]} | {r['karat']} | {r['weight_g']} g | ${r['price_usd']:,.2f} | "
            f"{r['verified_on']} | [link]({r['source_url']}) |"
        )
    L.append("")
    L.append("### Reading this table\n")
    L.append(
        f"- **Rows 1–{below}** are the only men's entries in the verified retail channels this project could "
        "confirm below $4,861/pure-gold-oz. All three are **Midwest Jewellery closeout men's ring mountings** "
        "(setting-only, solid 14K gold, gram weight published on the product page). They sit **9–18% below "
        "melt**, which is closeout pricing, not normal retail."
    )
    L.append(
        "- **Row 4** (Provident Metals, Nebü 10.5 g 24K men's curved ring, size 8) is the cheapest 24K men's "
        "ring verified anywhere in this project, at +34% over melt."
    )
    L.append(
        "- **Rows 5–7** are Costco; prices re-verified live on 2026-08-27. The 2.5 mm band had repriced "
        "+36% since 2026-08-19, which is what pushed it out of the below-threshold set."
    )
    L.append(
        "- **Rows 8+** are Ritani 18K men's bands at +87% to +240% over melt — included to show the true "
        "shape of the market."
    )
    L.append(
        "- The `vs melt` column is why a 50-entry target is unreachable: the threshold is melt + 5.35%, and "
        "every channel measured sits at +16% or higher, except US closeout mountings which sell below melt."
    )

    md_path = os.path.join(ROOT, "docs", "MENS_LEADERBOARD.md")
    json_path = os.path.join(ROOT, "docs", "data", "mens_price_per_oz_leaderboard.json")
    os.makedirs(os.path.dirname(json_path), exist_ok=True)
    open(md_path, "w").write("\n".join(L) + "\n")
    json.dump(payload, open(json_path, "w"), indent=1)

    print(f"wrote {md_path}")
    print(f"wrote {json_path}")
    print(
        f"  {n} men's/unisex rows with price/oz | {below} below ${THRESHOLD:,.0f} | "
        f"{payload['rows_with_price_per_gold_oz']} of {len(rows)} rows have price/oz"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
